//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubAdministration.Resources.modules.club {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubAdministration.Resources.modules.club.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در نمايش جلسات تمرين كلاس آموزشي.
        /// </summary>
        public static string coachNotFound {
            get {
                return ResourceManager.GetString("coachNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in fetching training class records.
        /// </summary>
        public static string coachShowError {
            get {
                return ResourceManager.GetString("coachShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلاس آموزشي درخواستي در سيستم ثبت نشده است.
        /// </summary>
        public static string playerNotFound {
            get {
                return ResourceManager.GetString("playerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشكل در نمايش بازيكنان كلاس آموزشي.
        /// </summary>
        public static string playerShowError {
            get {
                return ResourceManager.GetString("playerShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در نمايش جلسات تمرين كلاس آموزشي.
        /// </summary>
        public static string sessionNotFound {
            get {
                return ResourceManager.GetString("sessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in fetching training class records.
        /// </summary>
        public static string sessionShowError {
            get {
                return ResourceManager.GetString("sessionShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلاس آموزشي درخواستي در سيستم ثبت نشده است.
        /// </summary>
        public static string trainingNotFound {
            get {
                return ResourceManager.GetString("trainingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشكل در نمايش بازيكنان كلاس آموزشي.
        /// </summary>
        public static string trainingShowError {
            get {
                return ResourceManager.GetString("trainingShowError", resourceCulture);
            }
        }
    }
}
